# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_ingest.ipynb.

# %% auto 0
__all__ = ['read']

# %% ../nbs/00_ingest.ipynb 3
import re
import pandas as pd        
import numpy as np 
import traceback
import datetime
from cerberus import Validator
from urllib.error import URLError

# %% ../nbs/00_ingest.ipynb 4
def read(file_type: str, file_path: str) -> tuple:
    """
    This function read  helps  to read any of a csv,excel and parquet file,
    and returns a pandas dataframe.

    Parameters
    ----------
    file_type: file type must be one of csv,excel or parquet format.
    file: file path.

    Returns
    -------
        if   errors - function returns tuple with boolean value  "False" and dictionary with errors 
        if no errors - function returns tuple with boolean value  "True" and  dataframe

    """

    report_dict = {}
    errors = {}
    emptydf = pd.DataFrame()
    error_flag = False

    if file_type not in ['csv', 'excel', 'parquet']:
        errors["error"] = "unsupported file format please pass one of csv,excel or parquet types"
        return (False, errors, emptydf)

    # first set of checks on file missing, corrupted, etc.
    try:
        if file_type == 'csv':
            df = pd.read_csv(file_path)
        if file_type == 'excel':
            df = pd.read_excel(file_path)
        if file_type == 'parquet':
            df = pd.read_parquet(file_path)

    except FileNotFoundError as e:
        errors["error"] = (
            "File not found please check file path", traceback.format_exc())
        error_flag = True
    except URLError as e1:
        errors["error"] = ('URL not found,invalid URL', traceback.format_exc())
        error_flag = True
    except UnicodeDecodeError as e2:
        errors["error"] = (
            "corrupted data or wrong file format", traceback.format_exc())
        error_flag = True
    except ValueError as e3:
        errors["error"] = (
            "corrupted data or wrong file format", traceback.format_exc())
        error_flag = True
    except:
        errors["error"] = ("UnKnow error occured ", traceback.format_exc())
        error_flag = True

    if error_flag:
        return (False, errors)
    return (True, df)
